Enable MobStatz: true
Zombies:
    Enabled: true
    Zombie Kill Message: "&3You Killed A Zombie! Yay!"
    Zombie Kill Broadcast: "<player> has killed a zombie!"
    Command on Kill: true
    Command: give <player> diamond 10
    Zombie Kills: 0
Creeper:
    Enabled: true
    Creeper Kill Message: "&3You Killed A Creeper! Yay!"
    Creeper Kill Broadcast: "<player> has killed a Creeper!"
    Command on Kill: true
    Command: give <player> diamond 10
    Creeper Kills: 0
Skeleton:
    Enabled: true
    Skeleton Kill Message: "&3You Killed A Skeleton! Yay!"
    Skeleton Kill Broadcast: "<player> has killed a Skeleton!"
    Command on Kill: true
    Command: give <player> diamond 10
    Skeleton Kills: 0
Spider:
    Enabled: true
    Spider Kill Message: "&3You Killed A Spider! Yay!"
    Spider Kill Broadcast: "<player> has killed a Spider!"
    Command on Kill: true
    Command: give <player> diamond 10
    Spider Kills: 0
Blaze:
    Enabled: true
    Blaze Kill Message: "&3You Killed A Blaze! Yay!"
    Blaze Kill Broadcast: "<player> has killed a Blaze!"
    Command on Kill: true
    Command: give <player> diamond 10
    Blaze Kills: 0
Slime:
    Enabled: true
    Slime Kill Message: "&3You Killed A Slime! Yay!"
    Slime Kill Broadcast: "<player> has killed a Slime!"
    Command on Kill: true
    Command: give <player> diamond 10
    Slime Kills: 0
Cave_Spider:
    Enabled: true
    Cave_Spider Kill Message: "&3You Killed A Cave Spider! Yay!"
    Cave_Spider Kill Broadcast: "<player> has killed a Cave Spider!"
    Command on Kill: true
    Command: give <player> diamond 10
    Cave_Spider Kills: 0
Elder_Guardian:
    Enabled: true
    Elder_Guardian Kill Message: "&3You Killed A Elder Guardian! Yay!"
    Elder_Guardian Kill Broadcast: "<player> has killed a Elder Guardian!"
    Command on Kill: true
    Command: give <player> diamond 10
    Elder_Guardian Kills: 0
Ender_Dragon:
    Enabled: true
    Ender_Dragon Kill Message: "&3You Killed A Ender Dragon! Yay!"
    Ender_Dragon Kill Broadcast: "<player> has killed a Ender Dragon!"
    Command on Kill: true
    Command: give <player> diamond 10
    Ender_Dragon Kills: 0
Enderman:
    Enabled: true
    Enderman Kill Message: "&3You Killed A Enderman! Yay!"
    Enderman Kill Broadcast: "<player> has killed a Enderman!"
    Command on Kill: true
    Command: give <player> diamond 10
    Enderman Kills: 0
Endermite:
    Enabled: true
    Endermite Kill Message: "&3You Killed A Endermite! Yay!"
    Endermite Kill Broadcast: "<player> has killed a Endermite!"
    Command on Kill: true
    Command: give <player> diamond 10
    Endermite Kills: 0
Giant:
    Enabled: true
    Giant Kill Message: "&3You Killed A Giant! Yay!"
    Giant Kill Broadcast: "<player> has killed a Giant!"
    Command on Kill: true
    Command: give <player> diamond 10
    Giant Kills: 0
Guardian:
    Enabled: true
    Guardian Kill Message: "&3You Killed A Guardian! Yay!"
    Guardian Kill Broadcast: "<player> has killed a Guardian!"
    Command on Kill: true
    Command: give <player> diamond 10
    Guardian Kills: 0
Husk:
    Enabled: true
    Husk Kill Message: "&3You Killed A Husk! Yay!"
    Husk Kill Broadcast: "<player> has killed a Husk!"
    Command on Kill: true
    Command: give <player> diamond 10
    Husk Kills: 0
Magma_Cube:
    Enabled: true
    Magma_Cube Kill Message: "&3You Killed A Magma Cube! Yay!"
    Magma_Cube Kill Broadcast: "<player> has killed a Magma Cube!"
    Command on Kill: true
    Command: give <player> diamond 10
    Magma_Cube Kills: 0
Zombie_Pigman:
    Enabled: true
    Zombie_Pigman Kill Message: "&3You Killed A Zombie Pigman! Yay!"
    Zombie_Pigman Kill Broadcast: "<player> has killed a Zombie Pigman!"
    Command on Kill: true
    Command: give <player> diamond 10
    Zombie_Pigman Kills: 0
Polar_Bear:
    Enabled: true
    Polar_Bear Kill Message: "&3You Killed A Polar Bear! Yay!"
    Polar_Bear Kill Broadcast: "<player> has killed a Polar Bear!"
    Command on Kill: true
    Command: give <player> diamond 10
    Polar_Bear Kills: 0
Shulker:
    Enabled: true
    Shulker Kill Message: "&3You Killed A Shulker! Yay!"
    Shulker Kill Broadcast: "<player> has killed a Shulker!"
    Command on Kill: true
    Command: give <player> diamond 10
    Shulker Kills: 0
Silverfish:
    Enabled: true
    Silverfish Kill Message: "&3You Killed A Silverfish! Yay!"
    Silverfish Kill Broadcast: "<player> has killed a Silverfish!"
    Command on Kill: true
    Command: give <player> diamond 10
    Silverfish Kills: 0
Witch:
    Enabled: true
    Witch Kill Message: "&3You Killed A Witch! Yay!"
    Witch Kill Broadcast: "<player> has killed a Witch!"
    Command on Kill: true
    Command: give <player> diamond 10
    Witch Kills: 0
Wither:
    Enabled: true
    Wither Kill Message: "&3You Killed A Wither! Yay!"
    Wither Kill Broadcast: "<player> has killed a Wither!"
    Command on Kill: true
    Command: give <player> diamond 10
    Wither Kills: 0
Wither_Skeleton:
    Enabled: true
    Wither_Skeleton Kill Message: "&3You Killed A Wither Skeleton! Yay!"
    Wither_Skeleton Kill Broadcast: "<player> has killed a Wither Skeleton!"
    Command on Kill: true
    Command: give <player> diamond 10
    Wither_Skeleton Kills: 0
Zombie_Villager:
    Enabled: true
    Zombie_Villager Kill Message: "&3You Killed A Zombie Villager! Yay!"
    Zombie_Villager Kill Broadcast: "<player> has killed a Zombie Villager!"
    Command on Kill: true
    Command: give <player> diamond 10
    Zombie_Villager Kills: 0
Bat:
    Enabled: true
    Bat Kill Message: "&3You Killed A Bat! Yay!"
    Bat Kill Broadcast: "<player> has killed a Bat!"
    Command on Kill: true
    Command: give <player> diamond 10
    Bat Kills: 0
Chicken:
    Enabled: true
    Chicken Kill Message: "&3You Killed A Chicken! Yay!"
    Chicken Kill Broadcast: "<player> has killed a Chicken!"
    Command on Kill: true
    Command: give <player> diamond 10
    Chicken Kills: 0
Cow:
    Enabled: true
    Cow Kill Message: "&3You Killed A Cow! Yay!"
    Cow Kill Broadcast: "<player> has killed a Cow!"
    Command on Kill: true
    Command: give <player> diamond 10
    Cow Kills: 0
Donkey:
    Enabled: true
    Donkey Kill Message: "&3You Killed A Donkey! Yay!"
    Donkey Kill Broadcast: "<player> has killed a Donkey!"
    Command on Kill: true
    Command: give <player> diamond 10
    Donkey Kills: 0
Horse:
    Enabled: true
    Horse Kill Message: "&3You Killed A Horse! Yay!"
    Horse Kill Broadcast: "<player> has killed a Horse!"
    Command on Kill: true
    Command: give <player> diamond 10
    Horse Kills: 0
Iron_Golem:
    Enabled: true
    Iron_Golem Kill Message: "&3You Killed A Iron Golem! Yay!"
    Iron_Golem Kill Broadcast: "<player> has killed a Iron Golem!"
    Command on Kill: true
    Command: give <player> diamond 10
    Iron_Golem Kills: 0
Llama:
    Enabled: true
    Llama Kill Message: "&3You Killed A Llama! Yay!"
    Llama Kill Broadcast: "<player> has killed a Llama!"
    Command on Kill: true
    Command: give <player> diamond 10
    Llama Kills: 0
Mule:
    Enabled: true
    Mule Kill Message: "&3You Killed A Mule! Yay!"
    Mule Kill Broadcast: "<player> has killed a Mule!"
    Command on Kill: true
    Command: give <player> diamond 10
    Mule Kills: 0
Mooshroom:
    Enabled: true
    Mooshroom Kill Message: "&3You Killed A Mooshroom! Yay!"
    Mooshroom Kill Broadcast: "<player> has killed a Mooshroom!"
    Command on Kill: true
    Command: give <player> diamond 10
    Mooshroom Kills: 0
Ocelot:
    Enabled: true
    Ocelot Kill Message: "&3You Killed A Ocelot! Yay!"
    Ocelot Kill Broadcast: "<player> has killed a Ocelot!"
    Command on Kill: true
    Command: give <player> diamond 10
    Ocelot Kills: 0
Pig:
    Enabled: true
    Pig Kill Message: "&3You Killed A Pig! Yay!"
    Pig Kill Broadcast: "<player> has killed a Pig!"
    Command on Kill: true
    Command: give <player> diamond 10
    Pig Kills: 0
Player:
    Enabled: true
    Player Kill Message: "&3You Killed A Player! Yay!"
    Player Kill Broadcast: "<player> has killed a Player!"
    Command on Kill: true
    Command: give <player> diamond 10
    Player Kills: 0
Rabbit:
    Enabled: true
    Rabbit Kill Message: "&3You Killed A Rabbit! Yay!"
    Rabbit Kill Broadcast: "<player> has killed a Rabbit!"
    Command on Kill: true
    Command: give <player> diamond 10
    Rabbit Kills: 0
Sheep:
    Enabled: true
    Sheep Kill Message: "&3You Killed A Sheep! Yay!"
    Sheep Kill Broadcast: "<player> has killed a Sheep!"
    Command on Kill: true
    Command: give <player> diamond 10
    Sheep Kills: 0
Snowman:
    Enabled: true
    Snowman Kill Message: "&3You Killed A Snowman! Yay!"
    Snowman Kill Broadcast: "<player> has killed a Snowman!"
    Command on Kill: true
    Command: give <player> diamond 10
    Snowman Kills: 0
Stray:
    Enabled: true
    Stray Kill Message: "&3You Killed A Stray! Yay!"
    Stray Kill Broadcast: "<player> has killed a Stray!"
    Command on Kill: true
    Command: give <player> diamond 10
    Stray Kills: 0
Vex:
    Enabled: true
    Vex Kill Message: "&3You Killed A Vex! Yay!"
    Vex Kill Broadcast: "<player> has killed a Vex!"
    Command on Kill: true
    Command: give <player> diamond 10
    Vex Kills: 0
Villager:
    Enabled: true
    Villager Kill Message: "&3You Killed A Villager! Yay!"
    Villager Kill Broadcast: "<player> has killed a Villager!"
    Command on Kill: true
    Command: give <player> diamond 10
    Villager Kills: 0
Vindicator:
    Enabled: true
    Vex Kill Message: "&3You Killed A Vex! Yay!"
    Vex Kill Broadcast: "<player> has killed a Vex!"
    Command on Kill: true
    Command: give <player> diamond 10
    Vex Kills: 0
Wolf:
    Enabled: true
    Vex Kill Message: "&3You Killed A Vex! Yay!"
    Vex Kill Broadcast: "<player> has killed a Vex!"
    Command on Kill: true
    Command: give <player> diamond 10
    Vex Kills: 0