# 
#                                       #
#        Only Buy Buckets v1.0          #
#         by:THE_LLAMA_PRINCE           #
#                                       #
Only Buy Buckets Version: 1.0
Enable Only Buy Buckets: true
Message: YOU DO NOT HAVE PERMISSION
